routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/home',App\Http\Controllers\VehiculoController::class)->middleware('auth');

Route::resource('/vehiculos',App\Http\Controllers\VehiculoController::class)->middleware('auth');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/Vehiculo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Vehiculo
 *
 * @property $id
 * @property $placas
 * @property $marca
 * @property $modelo
 * @property $color
 * @property $tipo_combustible
 * @property $fecha_adquisicion
 * @property $estatus
 * @property $user_id
 * @property $created_at
 * @property $updated_at
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Vehiculo extends Model
{
    
    static $rules = [
		'placas' => 'required',
		'marca' => 'required',
		'modelo' => 'required',
		'tipo_combustible' => 'required',
		'fecha_adquisicion' => 'required',
		'estatus' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['placas','marca','modelo','color','tipo_combustible','fecha_adquisicion','estatus','user_id'];



}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/VehiculoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Vehiculo;
use App\Models\User;
use Illuminate\Http\Request;

/**
 * Class VehiculoController
 * @package App\Http\Controllers
 */
class VehiculoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vehiculos = Vehiculo::paginate();

        return view('vehiculo.index', compact('vehiculos'))
            ->with('i', (request()->input('page', 1) - 1) * $vehiculos->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $vehiculo = new Vehiculo();
        return view('vehiculo.create', compact('vehiculo'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Vehiculo::$rules);

        $vehiculo = Vehiculo::create($request->all());

        return redirect()->route('vehiculos.index')
            ->with('success', 'Vehículo creado con éxito.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $vehiculo = Vehiculo::find($id);

        return view('vehiculo.show', compact('vehiculo'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $vehiculo = Vehiculo::find($id);
        $users = User::paginate();

        return view('vehiculo.edit', compact('vehiculo','users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Vehiculo $vehiculo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Vehiculo $vehiculo)
    {
        request()->validate(Vehiculo::$rules);

        $vehiculo->update($request->all());

        return redirect()->route('vehiculos.index')
            ->with('success', 'Actualizado Correctamente');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $vehiculo = Vehiculo::find($id)->delete();

        return redirect()->route('vehiculos.index')
            ->with('success', 'Vehiculo Eliminado!');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->

                    @if(Auth::check())
                        <ul class="navbar-nav mr-auto">
                            <a class="nav-link" href="{{ route('vehiculos.index') }}">{{ __('Vehiculos') }}</a>
                        </ul>
                    @endif
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Ingresar') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Registrar') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Salir') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/vehiculo/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Vehiculo
@endsection

@section('content')
    <section class="content container">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Vehiculo</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('vehiculos.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('vehiculo.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/vehiculo/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Vehiculo
@endsection

@section('content')
    <section class="content container">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title"><b>Evaluación del Vehículo</b></span>
                    </div>
                    <div class="card-header">
                        <label id="asignacion"></label>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('vehiculos.update', $vehiculo->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf


                            <div class="box box-info padding-1">
                                <div class="box-body">
                                    
                                    <div class="form-group">
                                        {{ Form::label('placas') }}
                                        {{ Form::text('placas', $vehiculo->placas, ['class' => 'form-control' . ($errors->has('placas') ? ' is-invalid' : ''), 'placeholder' => 'Placas']) }}
                                        {!! $errors->first('placas', '<div class="invalid-feedback">:message</p>') !!}
                                    </div>
                                    <div class="form-group">
                                        {{ Form::label('marca') }}
                                        {{ Form::text('marca', $vehiculo->marca, ['class' => 'form-control' . ($errors->has('marca') ? ' is-invalid' : ''), 'placeholder' => 'Marca']) }}
                                        {!! $errors->first('marca', '<div class="invalid-feedback">:message</p>') !!}
                                    </div>
                                    <div class="form-group">
                                        {{ Form::label('modelo') }}
                                        {{ Form::text('modelo', $vehiculo->modelo, ['class' => 'form-control' . ($errors->has('modelo') ? ' is-invalid' : ''), 'placeholder' => 'Modelo']) }}
                                        {!! $errors->first('modelo', '<div class="invalid-feedback">:message</p>') !!}
                                    </div>
                                    <div class="form-group">
                                        {{ Form::label('color') }}
                                        {{ Form::text('color', $vehiculo->color, ['class' => 'form-control' . ($errors->has('color') ? ' is-invalid' : ''), 'placeholder' => 'Color']) }}
                                        {!! $errors->first('color', '<div class="invalid-feedback">:message</p>') !!}
                                    </div>
                                    <div class="form-group">
                                        <label>Tipo de Combustible</label>
                                        <select class="form-control" name="tipo_combustible" id="tipo_combustible">
                                            <option value="1">Gasolina</option>
                                            <option value="2">Diesel</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label>Fecha de Adquisición</label>
                                        {{ Form::text('fecha_adquisicion', $vehiculo->fecha_adquisicion, ['class' => 'form-control' . ($errors->has('fecha_adquisicion') ? ' is-invalid' : ''), 'placeholder' => 'Fecha de Adquisición']) }}
                                        {!! $errors->first('fecha_adquisicion', '<div class="invalid-feedback">:message</p>') !!}
                                    </div>
                                    <div class="form-group">
                                        <label>Fecha de Alta</label>
                                        <input class="form-control" type="text" value="{{ $vehiculo->created_at}}"readonly>
                                    </div>
                                    <div class="form-group">
                                        <label>Estatus</label>
                                        <select class="form-control" name="estatus" id="estatus" onchange="changeStatus()">
                                            <option value="1">Enviado</option>
                                            <option value="2">Asignado</option>
                                            <option value="3">Disponible</option>
                                            <option value="4">Baja</option>
                                        </select>
                                    </div>
                                         
                                    <div class="form-group" id ="empleados" style="display:none">
                                        <label>Asignar a un Empleado</label>
                                        <select class="form-control" name="user_id" id="user_id" >
                                            <option value="0">Elige un empleado</option>
                                            @foreach ($users as $user)
                                                <option value="{{$user->id}}">{{$user->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    

                                </div>
                                <div class="box-footer mt20 float-right">
                                    <br>
                                    <button type="submit" class="btn btn-primary">Guardar</button>
                                    <a href="{{ route('vehiculos.index') }}" class="btn btn-light"  data-placement="left">Cancelar</a>
                                </div>
                            </div>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script type="text/javascript">
        function changeStatus() {
            if(document.getElementById("estatus").value==2){
                document.getElementById("empleados").style.display='inline';
            }
            else{
                document.getElementById("user_id").value=0;
                document.getElementById("empleados").style.display="none";
            }
        }

        function load() {
            var tc= '<?= $vehiculo->tipo_combustible?>';
            document.getElementById("tipo_combustible").value = tc;
            var e= '<?= $vehiculo->estatus?>';
            document.getElementById("estatus").value = e;
            var emp= '<?= $vehiculo->user_id?>';
            document.getElementById("user_id").value = emp;
            if(document.getElementById("user_id").value > 0)
            document.getElementById("asignacion").innerHTML = "Vehículo asignado a: " + document.getElementById("user_id").options[document.getElementById("user_id").selectedIndex].text;
            else
            document.getElementById("asignacion").innerHTML = "Vehículo sin asignar" 
            
            
            if(document.getElementById("estatus").value==2){
                document.getElementById("empleados").style.display='inline';
            }
        }
        window.onload = load;

    </script>

    @endsection

resources/views/vehiculo/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('placas') }}
            {{ Form::text('placas', $vehiculo->placas, ['class' => 'form-control' . ($errors->has('placas') ? ' is-invalid' : ''), 'placeholder' => 'Placas']) }}
            {!! $errors->first('placas', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('marca') }}
            {{ Form::text('marca', $vehiculo->marca, ['class' => 'form-control' . ($errors->has('marca') ? ' is-invalid' : ''), 'placeholder' => 'Marca']) }}
            {!! $errors->first('marca', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('modelo') }}
            {{ Form::text('modelo', $vehiculo->modelo, ['class' => 'form-control' . ($errors->has('modelo') ? ' is-invalid' : ''), 'placeholder' => 'Modelo']) }}
            {!! $errors->first('modelo', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('color') }}
            {{ Form::text('color', $vehiculo->color, ['class' => 'form-control' . ($errors->has('color') ? ' is-invalid' : ''), 'placeholder' => 'Color']) }}
            {!! $errors->first('color', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            <label>Tipo de Combustible</label>
            <select class="form-control" placeholder="Color" name="tipo_combustible">
                <option value="1">Gasolina</option>
                <option value="2">Diesel</option>
            </select>
        </div>
        <div class="form-group">
            <label>Fecha de Adquisición</label>
            {{ Form::date('fecha_adquisicion', $vehiculo->fecha_adquisicion, ['class' => 'form-control' . ($errors->has('fecha_adquisicion') ? ' is-invalid' : ''), 'placeholder' => 'Fecha de Adquisición']) }}
            {!! $errors->first('fecha_adquisicion', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            <input type="hidden" name="estatus" value="1">
        </div>
    </div>
    <div class="box-footer mt20 float-right">
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a href="{{ route('vehiculos.index') }}" class="btn btn-light"  data-placement="left">Cancelar</a>
    </div>
</div>

resources/views/vehiculo/index.blade.php
@extends('layouts.app')

@section('template_title')
    Vehiculo
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Vehículos') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('vehiculos.create') }}" class="btn btn-success btn-sm float-right"  data-placement="left">
                                  {{ __('Nuevo') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>
										<th>Placas</th>
										<th>Marca</th>
										<th>Modelo</th>
                                        <th>Estatus</th>

                                        <th>Acción</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($vehiculos as $vehiculo)
                                        <tr>
                                            <td>{{ ++$i }}</td>
											<td>{{ $vehiculo->placas }}</td>
											<td>{{ $vehiculo->marca }}</td>
											<td>{{ $vehiculo->modelo }}</td>
                                            @if ($vehiculo->estatus == 1)
											    <td><span class="badge badge-primary">Enviado</span></td>
                                            @elseif ($vehiculo->estatus == 2)
                                                <td><span class="badge badge-light">Asignado</span></td>
                                            @elseif ($vehiculo->estatus == 3)
                                                <td><span class="badge badge-success">Disponible</span></td>
                                            @else
                                                <td><span class="badge badge-danger">Baja</span></td>
                                            @endif
                                            <td>
                                                <form action="{{ route('vehiculos.destroy',$vehiculo->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-warning" href="{{ route('vehiculos.edit',$vehiculo->id) }}"><i class="fa fa-fw fa-eye"></i> Evaluación</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Eliminar</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $vehiculos->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/vehiculo/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $vehiculo->name ?? 'Show Vehiculo' }}
@endsection

@section('content')
    <section class="content container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Evaluación del Vehículo</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('vehiculos.index') }}"> Volver</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Placas:</strong>
                            {{ $vehiculo->placas }}
                        </div>
                        <div class="form-group">
                            <strong>Marca:</strong>
                            {{ $vehiculo->marca }}
                        </div>
                        <div class="form-group">
                            <strong>Modelo:</strong>
                            {{ $vehiculo->modelo }}
                        </div>
                        <div class="form-group">
                            <strong>Color:</strong>
                            {{ $vehiculo->color }}
                        </div>
                        <div class="form-group">
                            <strong>Tipo de Combustible:</strong>
                            {{ $vehiculo->tipo_combustible }}
                        </div>
                        <div class="form-group">
                            <strong>Fecha de Adquisición:</strong>
                            {{ $vehiculo->fecha_adquisicion }}
                        </div>
                        <div class="form-group">
                            <strong>Fecha de Alta:</strong>
                            {{ $vehiculo->created_at }}
                        </div>
                        <div class="form-group">
                            @if ($vehiculo->estatus == 1)
                            <strong>Estatus: </strong><span class="badge badge-primary">Enviado</span>
                            @elseif ($vehiculo->estatus == 2)
                            <strong>Estatus: </strong><span class="badge badge-light">Asignado</span>
                            @elseif ($vehiculo->estatus == 3)
                            <strong>Estatus: </strong><span class="badge badge-success">Disponible</span>
                            @else
                            <strong>Estatus: </strong><span class="badge badge-danger">Baja</span>
                            @endif
                        </div>
                        @if ($vehiculo->estatus == 1 or $vehiculo->estatus == 3)
                            <form method="POST" action="{{ route('vehiculos.update', $vehiculo->id) }}"  role="form" enctype="multipart/form-data">    
                                <div class="form-group">
                                    <strong>Asignar a Empleado</strong>
                                    <select name="user_id" >
                                        <option value="0">Elige un empleado</option>
                                        @foreach ($users as $user)
                                            <option value="{{$user->id}}">{{$user->name}}</option>
                                        @endforeach
                                    </select>
                                    <input name="placas" type="hidden" value="{{ $vehiculo->placas }}">
                                    <input name="marca" type="hidden" value="{{ $vehiculo->marca }}">
                                    <input name="modelo" type="hidden" value="{{ $vehiculo->modelo }}">
                                    <input name="color" type="hidden" value="{{ $vehiculo->color }}">
                                    <input name="fecha_adquisicion" type="hidden" value="{{ $vehiculo->fecha_adquisicion }}">
                                    <input name="tipo_combustible" type="hidden" value="{{ $vehiculo->tipo_combustible }}">
                                    <input name="estatus" type="hidden" value="2">
                                    <button type="submit" class="btn btn-success">Guardar</button>
                                </div>
                            </form>
                        @endif

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection